### PR TITLE
Fix inline tag with code

### LINKED ISSUE #1871: Mismatched brackets work with interpolation
This should be an error:

```jade
p #[code= 'this is a piece of code'}
```

### PR DESCRIPTION
**Pull request by TimothyGu**
The cause of this problem is in how inline tags work: you encounter `#[`, then you take the rest of the line and feeds it into a new lexer. Using a special option `this.interpolated` and a flag `this.ended`, the child lexer returns whatever it can lex (i.e. the interpolated part) and the rest (after the interpolation) is fed back to the parent lexer from `child.input`.

For text, it works well, since can't really have `]` as a valid part of the text, so one can just use `indexOf(']')` for the ending index of the interpolation.

Right now for code, it just feeds the **entire** rest of the line to the token, which in many cases will not be valid JS and caught in the `assertExpression` below. Plus, with code one never knows when code
starts or ends, if the `']'` is in quotes or not. So one has to be cautious when consuming the strings, not using the crude `indexOf` check, which is what I am doing here.

This also fixes jadejs/jade#1871.

Depends on ForbesLindesay/character-parser#12.

This should be merged in conjunction with jadejs/jade#2049.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -690,13 +690,23 @@ Lexer.prototype = {
...
     if (captures = /^(!?=|-)[ \t]*([^\n]+)/.exec(this.input)) {
-      this.consume(captures[0].length);
       var flags = captures[1];
-      captures[1] = captures[2];
-      var tok = this.tok('code', captures[1]);
+      var code = captures[2];
+      var parsed, shortened = 0;
+      if (this.interpolated) {
+        try {
+          parsed = characterParser.parseUntil(code, ']');
```
Comment (ForbesLindesay) [inline index.js]: How does this handle code like:

``` jade
- var index = Math.floor(Math.random() * 3);
p #[strong= ['a', 'b', 'c'][index]];
```

We could use `characterParser.parseMax(code)` and then check that the next character is `]`?

File: index.js [hunk 2]
```diff
@@ -690,13 +690,23 @@ Lexer.prototype = {
...
+        }
+        shortened = code.length - parsed.end;
+        code = parsed.src;
+      }
+      this.consume(captures[0].length - shortened);
+      var tok = this.tok('code', code);
       tok.escape = flags.charAt(0) === '=';
       tok.buffer = flags.charAt(0) === '=' || flags.charAt(1) === '=';
-      if (tok.buffer) this.assertExpression(captures[1]);
+      if (tok.buffer) this.assertExpression(code);
```
Comment (ForbesLindesay) [inline index.js:708]: If `this.interpolated` is `true` we should probably add an assertion to check that the code is a valid statement/sequence of statements.  e.g. we should probably prevent the following (admittedly currently valid) jade.

``` jade
p #[- items.forEach(function (item) {]item#[- });]
```

Comment (TimothyGu) [inline index.js:708]: I think the better question is if we should support `#[- 'code']` syntax at all. Tag interpolation isn't designed for control flow.

If we decide to keep supporting `#[-`, then I see no reason why we should only support complete statements.

File: index.js (hunk 1 above)
Comment (TimothyGu) [inline index.js]: I did not want to use `parseMax`, since consider this case:

``` jade
p #[strong= ['a', 'b', 'c'][index]};
```

We could throw an error about "bracket mismatch,"  but that doesn't feel intuitive. One would expect the lexer to throw "no ending bracket found" since that is the most direct error.

And for this reason, I wrote ForbesLindesay/character-parser#12, which will allow `['a', 'b', 'c'][index]};` to be the source as long as there is a trailing `]`, and throw the correct error if not.

File: index.js (hunk 2 above)
Comment (ForbesLindesay) [inline index.js:708]: Lets drop support all together then
